apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/L-and-D-Management-System/LnD.git
    path: infra_new/helm
    targetRevision: HEAD
    helm:
      parameters:
        - name: frontendService.enabled
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: ld-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
