{{- if .Values.authService.enabled }}
{{- $local := .Values.authService }}
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  MONGO_URI: {{ $.Values.global.mongo.uri | quote }}
  JWT_SECRET: {{ $.Values.global.jwtSecret | quote }}

{{- end }}

