{{- if .Values.userService.enabled }}
{{- $local := .Values.userService }}
---
apiVersion: v1
kind: Secret
metadata:
  name: user-secret
type: Opaque
stringData:
  MONGO_URI: {{ $.Values.global.mongo.uri | quote }}
  JWT_SECRET: {{ $.Values.global.jwtSecret | quote }}

{{- end }}

