apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-training-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/L-and-D-Management-System/LnD.git
    targetRevision: HEAD
    path: gitops/charts/training-service
    helm:
      valueFiles: ["../../values-prod.yaml", "values.yaml"]
  destination: {server: "https://kubernetes.default.svc", namespace: "ld-prod"}
  syncPolicy: {automated: {prune: true, selfHeal: true}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-attendance-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/L-and-D-Management-System/LnD.git
    targetRevision: HEAD
    path: gitops/charts/attendance-service
    helm:
      valueFiles: ["../../values-prod.yaml", "values.yaml"]
  destination: {server: "https://kubernetes.default.svc", namespace: "ld-prod"}
  syncPolicy: {automated: {prune: true, selfHeal: true}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-frontend-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/L-and-D-Management-System/LnD.git
    targetRevision: HEAD
    path: gitops/charts/frontend-service
    helm:
      valueFiles: ["../../values-prod.yaml", "values.yaml"]
  destination: {server: "https://kubernetes.default.svc", namespace: "ld-prod"}
  syncPolicy: {automated: {prune: true, selfHeal: true}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/L-and-D-Management-System/LnD.git
    targetRevision: HEAD
    path: gitops/charts/mongodb
    helm:
      valueFiles: ["../../values-prod.yaml", "values.yaml"]
  destination: {server: "https://kubernetes.default.svc", namespace: "ld-prod"}
  syncPolicy: {automated: {prune: true, selfHeal: true}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/L-and-D-Management-System/LnD.git
    targetRevision: HEAD
    path: gitops/charts/gateway
    helm:
      valueFiles: ["../../values-prod.yaml"]
  destination: {server: "https://kubernetes.default.svc", namespace: "ld-prod"}
  syncPolicy: {automated: {prune: true, selfHeal: true}}
