global:
  namespace: ld-dev
  domain: dev.13.234.38.101
  mongo:
    uri: "mongodb://mongodb-svc:27017/training_dev_db"
  jwtSecret: "devsecret"
  imagePullPolicy: Always

nodePort: 30081
replicaCount: 1

replicaCount: 1

# Remove resource requests so they always fit
resources: {}

# Use Recreate strategy to free up memory immediately during updates
strategy:
  type: Recreate
