global:
  namespace: ld-dev
  domain: dev.13.234.38.101
  mongo:
    uri: "mongodb://mongodb-svc.ld-dev:27017/training_dev_db"
  jwtSecret: "devsecret"
  imagePullPolicy: Always

replicaCount: 1

mongodb:
  resources:
    limits:
      cpu: "100m"
      memory: "256Mi"
    requests:
      cpu: "50m"
      memory: "128Mi"
  # Lower replicas for Dev to save resources
