{{- if .Values.attendanceService.enabled }}
{{- $local := .Values.attendanceService }}
---
apiVersion: v1
kind: Secret
metadata:
  name: attendance-secret
type: Opaque
stringData:
  MONGO_URI: {{ $.Values.global.mongo.uri | quote }}
  JWT_SECRET: {{ $.Values.global.jwtSecret | quote }}

{{- end }}

