apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "auth-service.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  PORT: "{{ .Values.service.port }}"
  NODE_ENV: "production"
  USER_SERVICE_URL: "http://user-svc:3002"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  MONGO_URI: {{ .Values.global.mongo.uri | quote }}
  JWT_SECRET: {{ .Values.global.jwtSecret | quote }}
