{{- if .Values.trainingService.enabled }}
{{- $local := .Values.trainingService }}
---
apiVersion: v1
kind: Secret
metadata:
  name: training-secret
type: Opaque
stringData:
  MONGO_URI: {{ $.Values.global.mongo.uri | quote }}
  JWT_SECRET: {{ $.Values.global.jwtSecret | quote }}

{{- end }}

